name: Build and publish

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle and Publish artifact
        run: ./gradlew build publish --console=plain
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
